[tool.ruff]
line-length = 120
target-version = "py312"

exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".venv",
    "venv",
    ".mypy_cache",
    ".pytest_cache",
    "migrations",
    ".eggs",
    "*.egg-info",
    "*.pyi",
]

[tool.ruff.lint]
select = ["E", "F", "W", "C90"]
extend-select = ["B", "D", "I", "S"]
extend-ignore = ["E203", "D100", "D101", "D102", "D103", "D107", "C901", "S108", "S311"]

[tool.ruff.lint.isort]
known-first-party = ["py"]

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["py"]
src_paths = ["."]
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob = ["*/migrations/*", "*/venv/*", "*.pyi"]
